on:
  push: # Pushes to master
    branches:
      - master
  pull_request: # PR to master
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    environment: Sonar cloud # Imperative to recognize the secrets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Test and coverage
        run: npm run sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by Github
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Defined by us on SonarCloud
